spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yunke
    username: root
    password: 123456

server:
  port: 8080
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    #mybatis-plus默认下划线自动转化为驼峰
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: mark # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
